### ISSUE TITLE
vendor.js:1 Uncaught SyntaxError: Unexpected token <

### ISSUE THREAD

**Issue by janisii** [huwcarwyn/react-laravel-boilerplate#1]
Hi!

I want to try your boilerplate react app. I get this error. What could that mean?
"vendor.js:1 Uncaught SyntaxError: Unexpected token <"

It detects error for the first line of the app.blade.php

Thanks.

**Comment by huwcarwyn** [comment]
So this is an error in development, in production I split the javascript into two files, vendor.js and app.js. This allows me to cache the library files like react/react-router etc in vendor.js, since these don't get updated as often as app.js.

In development however, I only compile the JS into app.js (helps with storybook). But I still try to include vendor.js. The unexpected < is the start of the laravel 404 page.

This error shouldn't be harmful, and I might conditionally load vendor.js in the future,

Thanks for trying out my boilerplate by the way!

**Comment by huwcarwyn** [comment]
Would you be interested in me filling out a wiki going into a bit more detail about every part of the boilerplate?

**Comment by janisii** [comment]
Yes! That would be really great. This could help a lot to those, who would like to use your boilerplate. Thanks.
